admin:
    resource: "@ApiBundle/Resources/config/admin.routing.xml"
    host:     "%admin_host%"

manager:
    resource: "@ApiBundle/Resources/config/manager.routing.xml"
    host:     "%manager_host%"

master:
    resource: "@ApiBundle/Resources/config/master.routing.xml"
    host:     "%master_host%"

partner:
    resource: "@ApiBundle/Resources/config/partner.routing.xml"
    host:     "%partner_host%"

logout:
    path:     /logout
