# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        admin_provider:
            entity:
                class: ModelBundle:Admin
        master_provider:
            entity:
                class: ModelBundle:Master
        partner_provider:
            entity:
                class: ModelBundle:Partner

    encoders:
        Polonairs\Dialtime\ModelBundle\Entity\Admin:
            algorithm: bcrypt
            cost: 12
        Polonairs\Dialtime\ModelBundle\Entity\Master:
            algorithm: bcrypt
            cost: 12
        Polonairs\Dialtime\ModelBundle\Entity\Partner:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            host: "%admin_host%"
            provider: admin_provider
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /cabinet
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
        master:
            host: "%master_host%"
            provider: master_provider
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /cabinet
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
        partner:
            host: "%partner_host%"
            provider: partner_provider
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /cabinet
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet, roles: ROLE_USER }