# parameters 
parameters: 
    database_host: ~
    database_port: ~
    database_name: ~
    database_user: ~
    database_password: ~
    secret: ~
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    admin_host: ~
    master_host: ~
    partner_host: ~
    static_host: ~